apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: secure-mfa-backup
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  horizontalPodAutoscalerSpec:
    minReplicas: 1
    maxReplicas: 3
