apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: pwn-super-secure-prison-2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
