apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: crypto-guacamole
spec:
  deployed: true
  powDifficultySeconds: 1
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
