apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: crypto-textbook-2
spec:
  deployed: true
  powDifficultySeconds: 1
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 4455
        port: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
